### ISSUE TITLE
Output: "Still Gathering Statistics..."

### ISSUE THREAD

**Issue by luyi404** [YouEclipse/waka-box-go#35]
Hi, I am recently trying to use your project to get a waka-box in my README in Github profile. But when I finish every step in your introduction, I just get the "Still Gathering Statistics...", but when I check my WAKATIME dashboard, there are a lot of data in it, and I do enable the `Display code time publicly` and `Display languages, editors, os, categories publicly`.

The output in my README:

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/46224920/161292952-a56333da-efc4-4e6b-8c62-7090e6307cca.png">

The Raw file:

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/46224920/161293212-e30275f0-5915-432b-acae-fe796a80024e.png">

But I am sure I set the secret token and other parameters right. And the GitHub action runs well.

My workflow config file:

```
name: Update wakatime stats

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "5 0 * * *"

jobs:
  build:
    name: Update-waka-stats
    runs-on: ubuntu-latest
    env:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      UPDATE_OPTION: GIST_AND_MARKDOWN
      MARKDOWN_FILE: README.md
      GIST_ID: ce41b***********************997b48
      GIST_BARSTYLE: SOLIDLT
      GIST_BARLENGTH: -1
      GIST_TIMESTYLE: SHORT

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - name: Check out repo
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Clone and run waka-box
        run: |-
          git clone https://github.com/YouEclipse/waka-box-go.git
          cd waka-box-go && go build -o waka ./cmd/box/main.go
          mv ./waka ../ && cd .. && rm -rf waka-box-go/
      - name: Commit and push
        run: |-
          ./waka
          git config --global user.email "bot@github.com" && git config --global user.name "Waka-Bot"
          git diff
          git add README.md && git commit -m ":memo: update profile" || exit 0
          git pull && git push
```
